MODE_RECORD = "record"
MODE_TEST = "test"
MODE_OFF = "off"
USE_HTTPS = 'https'
USE_HTTP = 'http'
ALLOWED_DEPENDENCY_TYPES = ['NO_SQL_DB', 'SQL_DB', 'GRPC', 'HTTP_CLIENT']
ALLOWED_METHODS = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'OPTIONS', 'TRACE']