name: Deploy to PyPI

on:
  push:
    branches:
      - 'fix-workflow'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
      working-directory: ./

    - name: Build and publish to PyPI
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
      working-directory: ./
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
